//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWRoute
    {
        public int IDTWRoute { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> StartX { get; set; }
        public Nullable<int> StartY { get; set; }
        public Nullable<int> StopX { get; set; }
        public Nullable<int> StopY { get; set; }
        public Nullable<double> Mileage { get; set; }
        public Nullable<int> AverageSpeed { get; set; }
        public Nullable<int> FuelConsumption { get; set; }
        public Nullable<int> TravelWarrantID { get; set; }
    
        public virtual TravelWarrant TravelWarrant { get; set; }
    }
}
